inherit_from: "configs/scenes12/base_config.yaml"
Dataset:
  dataset_path: "/mnt/nas_54/datasets/nerf-loc/12scenes/office1/lounge"

scene:
  bound: [[-3.7, 3.0],[-1.9, 2.3],[-0.1, 2.1]]
  voxel_sdf: 0.06