inherit_from: "configs/scenes12/base_config.yaml"
Dataset:
  dataset_path: "/mnt/nas_54/datasets/nerf-loc/12scenes/office1/manolis"

scene:
  bound: [[-2.5, 2.3],[-3.3, 2.5],[-0.1, 2.8]]
  voxel_sdf: 0.06